apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ldap
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: 'cn=openshift,ou=users,dc=example,dc=com'
      bindPassword:
        name: ldap
      ca:
        name: ldap
      insecure: false
      url: 'ldap://ldap.example.com/ou=users,dc=example,dc=com?uid'
