# Place application workloads on app nodes.
# Do not place any workloads on master nodes.
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  name: cluster
spec:
  defaultNodeSelector: node-role.kubernetes.io/worker=
  mastersSchedulable: false
