apiVersion: v1
kind: Secret
metadata:
  name: api-cert
  namespace: openshift-config
stringData:
  tls.crt: |
    'Insert your PEM certificate here'
  tls.key: |
    'Insert your PEM private key here'
type: kubernetes.io/tls
