# Add API server certificate.
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
      namedCertificates:
        - names:
            - 'api.mycluster.example.com'
          servingCertificate:
            name: apiserver-cert
