apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ad
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - sAMAccountName
      bindDN: 'CN=OpenShift,OU=Service Accounts,OU=Users,DC=example,DC=com'
      bindPassword:
        name: ad
      ca:
        name: ad
      insecure: false
      url: 'ldaps://ad.example.com/ou=Users,dc=example,dc=com?sAMAccountName'
