apiVersion: logging.openshift.io/v1alpha1
kind: LogForwarding
metadata:
  name: instance
  namespace: openshift-logging
spec:
  disableDefaultForwarding: true
  outputs:
   - name: elasticsearch
     type: elasticsearch
     endpoint: elasticsearch.openshift-logging.svc:9200
     secret:
       name: fluentd
   - name: insecureforward
     type: forward
     endpoint: 10.128.4.58:24224
  pipelines:
   - name: container-logs
     inputSource: logs.app
     outputRefs:
     - elasticsearch
     - insecureforward
   - name: infra-logs
     inputSource: logs.infra
     outputRefs:
     - elasticsearch
     - insecureforward
   - name: audit-logs
     inputSource: logs.audit
     outputRefs:
     - elasticsearch
     - insecureforward
