apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  logStore:
    type: elasticsearch
    elasticsearch:
      nodeCount: 3
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      resources:
        # See also https://github.com/elastic/helm-charts/blob/master/elasticsearch/values.yaml
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 2Gi
      storage:
        storageClassName: gp2
        size: 200G
      redundancyPolicy: SingleRedundancy
  visualization:
    type: kibana
    kibana:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      resources:
        # See also https://github.com/elastic/helm-charts/blob/master/kibana/values.yaml
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 2Gi
      proxy:
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      replicas: 2
  curation:
    type: curator
    curator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      resources:
        limits:
          memory: 500Mi
        requests:
          cpu: 200m
          memory: 500Mi
      schedule: "*/10 * * * *"
  collection:
    logs:
      type: fluentd
      fluentd:
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 1Gi
